% GC transition matrix
% dimensions: [S, U, P, R] x [S, U, P, R]
gcTransMat = [-(lambda_u + lambda_p + lambda_r + recover_r + trt_r + ps_r) , ...
    recover_u + trt_u + ps_u , recover_p + trt_p + ps_p , ...
    recover_r + trt_r + ps_r; ...
    0 , -(recover_u + trt_u + ps_u) , 0 , 0 ; ...
    0 , 0 , -(recover_p + trt_p + ps_p) , 0; ...
    0 , 0 , 0 , -(recover_r + trt_r + ps_r)];